### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by Shubham191297** [MicrocontrollersAndMore/OpenCV_3_License_Plate_Recognition_Python#18]
File "C:\Users\Shubham.000\Desktop\OpenCV_3_License_Plate_Recognition_Python-master\DetectPlates.py", line 133, in findPossibleCharsInScene
    imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)   # find all contours

ValueError: need more than 2 values to unpack

**Comment by pristis** [comment]
Same issue here.

**Comment by techieph** [comment]
Same Issue Here too

runfile('G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python/Main.py', wdir='G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python')
Reloaded modules: DetectChars, Main, DetectPlates, Preprocess, PossiblePlate, PossibleChar
Traceback (most recent call last):

  File "<ipython-input-19-1c057e88ce82>", line 1, in <module>
    runfile('G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python/Main.py', wdir='G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python/Main.py", line 134, in <module>
    main()

  File "G:/ph_new/Projects/OpenCV_3_License_Plate_Recognition_Python/Main.py", line 38, in main
    listOfPossiblePlates = DetectPlates.detectPlatesInScene(imgOriginalScene)           # detect plates

  File "G:\ph_new\Projects\OpenCV_3_License_Plate_Recognition_Python\DetectPlates.py", line 43, in detectPlatesInScene
    listOfPossibleCharsInScene = findPossibleCharsInScene(imgThreshScene)

  File "G:\ph_new\Projects\OpenCV_3_License_Plate_Recognition_Python\DetectPlates.py", line 133, in findPossibleCharsInScene
    imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)   # find all contours

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Mayank2504** [comment]
@techieph yes it worked

**Comment by iNusz** [comment]
@techieph it works well!! 

but in 7 line you should change word 
DetectPlates.py -> DetectChars.py
